- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy the expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import role app-prereq from common
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir : /usr/share/nginx/html
    component: frontend
    app_user: root

- name: Reload service nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
    enabled: true