- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy the backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add application User
  ansible.builtin.user:
    name: expense

- name: Import role app-prereq from common
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir : /app
    component: backend
    app_user: expense

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: Copy backend startUP script
  ansible.builtin.template:
    src: run.sh
    dest: /app/run.sh

- name: Install mysql clint
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h 54.165.154.125 -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: Start backend service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true
    daemon-reload: yes

##