- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Disable nodejs default version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable nodejs 18 version
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: copy the backend service file
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add application User
  ansible.builtin.user:
    name: expense

- name: Import role app-prereq from common
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir : /app
    component: backend
    app_user: expense

- name: Download NodeJS Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Install mysql clint
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Load Schema
  ansible.builtin.shell: mysql -h 172.31.42.182 -uroot -p{{ lookup('amazon.aws.aws_ssm', '{{env}}.rds.password', region='us-east-1' ) }} < /app/schema/backend.sql
- name: Start Backend Service
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Import elk
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat