- name: Set HostName
  ansible.builtin.shell: set-hostname {{env}}-{{component}}

- name: Install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: copy the expense config file
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import role app-prereq from common
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir : /usr/share/nginx/html
    component: frontend
    app_user: root

- name: Reload service nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: reloaded
    enabled: true


- name: Import elk
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat

- name: Import prometheus node-exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter

- name: Install New Relic Agent
  ansible.builtin.shell: curl -Ls https://download.newrelic.com/install/newrelic-cli/scripts/install.sh | bash && sudo NEW_RELIC_API_KEY=NNRAK-K53OUULUSNMG63W6W8U75CUV74D NEW_RELIC_ACCOUNT_ID=4368081 /usr/local/bin/newrelic install -y -n infrastructure-agent-installer --tag {{component}}-{{env}}

- name: Install New Relic Nginx Agent
  ansible.builtin.dnf:
    name: nri-nginx
    state: installed

- name: Copy New Relic Nginx Agent Config File
  ansible.builtin.template:
    src: nr-nginx.yml
    dest: /etc/newrelic-infra/integrations.d/nginx-config.yml

- name: Copy New Relic Nginx Agent Log Shipper Config File
  ansible.builtin.template:
    src: nr-nginx-log.yml
    dest: /etc/newrelic-infra/logging.d/nginx-log.yml


    #NRAK-K53OUULUSNMG63W6W8U75CUV74D-- new relic nginx