- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: Upload Alert File to S3
  ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://bpk-prometheus-alert-rules/{{component}}-{{env}}.yml
