- name: Generate Alert YAML File
  ansible.builtin.template:
    src: alert-rules.yml
    dest: /tmp/{{component}}-{{env}}.yml

- name: Upload Alert File to S3
  ansible.builtin.shell: aws s3 cp /tmp/{{component}}-{{env}}.yml s3://bpk-alert-rules/{{component}}-{{env}}.yml


- name: Trigger Prometheus Reload Job
  ansible.builtin.shell: curl -u {{ lookup('amazon.aws.aws_ssm', 'jenkins.username', region='us-east-1' ) }}:{{ lookup('amazon.aws.aws_ssm', 'jenkins.password', region='us-east-1' ) }}  "http://172.31.43.220:8080/job/Prometheus-reload/build?token=prometheus-reload-alerts"
