route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email'
receivers:
  - name: email
    email_configs:
      - to: balubadipavan@gmail.com
        from: balubadipavan@gmail.com
        smarthost: "email-smtp.us-east-1.amazonaws.com:587"
        auth_username: AKIAYS2NQBF5NBSYTOQU
        auth_password: BMYXiZvVENy0bb9oWEu2fBEoFgixJ5s3mSTQDeWQW2r6
        require_tls: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']